version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry:
        patterns:
          - "opentelemetry-api"
          - "opentelemetry-exporter-prometheus"
          - "opentelemetry-sdk"
    ignore:
      - dependency-name: "sentry-sdk"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: "sentry-sdk"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "monthly"