# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: "Exciting New Features :tada:"
      labels:
        - enhancement
    - title: "Grafana Changes :bar_chart:"
      labels:
        - "grafana"
    - title: "Prometheus Changes :fire:"
      labels:
        - "prometheus"
    - title: "Bug Fixes :lady_beetle:"
      labels:
        - "bug"
    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: Dependencies
      labels:
        - dependencies
