{
 "title": "Meshtastic Packets",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Packet priority distribution over time",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(meshtastic_mesh_packet_priority[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Packet priority distribution",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(meshtastic_mesh_packet_priority[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Packet rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(meshtastic_mesh_packet_count{via_mqtt=\"False\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets by sending station & type (broadcast)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(from, from_long_name, type) (increase(meshtastic_mesh_packet_count{to=\"4294967295\"}[$__interval]))",
     "legendFormat": "{{from_long_name}} ({{from}}) - {{type}}"
    }
   ]
  },
  {
   "title": "Packets by talkers & type (unicast)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(to, from, to_long_name, from_long_name, type) (increase(meshtastic_mesh_packet_count{to!=\"4294967295\"}[$__interval]))",
     "legendFormat": "{{from_long_name}} ({{from}}) -> {{to_long_name}} ({{to}}) - {{type}}"
    }
   ]
  },
  {
   "title": "Packets by type",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(meshtastic_mesh_packet_count[$__interval])) by (type) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}