{
 "title": "Meshtastic Packets (Net)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Packet rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(meshtastic_mesh_packet_count_total{via_mqtt=\"false\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets by sending station & type (broadcast)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(from, from_long_name, type) (increase(meshtastic_mesh_packet_count_total{to=\"4294967295\"}[$__interval]))",
     "legendFormat": "{{from_long_name}} ({{from}}) - {{type}}"
    }
   ]
  },
  {
   "title": "Packets by talkers & type (unicast)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(to, from, to_long_name, from_long_name, type) (increase(meshtastic_mesh_packet_count_total{to!=\"4294967295\"}[$__interval]))",
     "legendFormat": "{{from_long_name}} ({{from}}) -> {{to_long_name}} ({{to}}) - {{type}}"
    }
   ]
  },
  {
   "title": "Packets by type",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(meshtastic_mesh_packet_count_total[$__interval])) by (type) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}