{
 "title": "Meshtastic Telemetry (Net)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "meshtastic_node_info_last_heard"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Battery level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_device_battery_level{node=~\"$node\"}[$__interval])",
     "legendFormat": "{{node_long_name}} ({{node}})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_environment_temperature{node=~\"$node\"}[$__interval])",
     "legendFormat": "{{node_long_name}} ({{node}})"
    }
   ]
  },
  {
   "title": "Barometric pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_environment_barometric_pressure{node=~\"$node\"}[$__interval]) / 1.333",
     "legendFormat": "{{node_long_name}} ({{node}})"
    }
   ]
  },
  {
   "title": "Channel util",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_device_channel_utilization{node=~\"$node\"}[$__interval])",
     "legendFormat": "{{node_long_name}} ({{node}})"
    }
   ]
  },
  {
   "title": "Air util tx",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_device_air_util_tx{node=~\"$node\"}[$__interval])",
     "legendFormat": "{{node_long_name}} ({{node}})"
    }
   ]
  },
  {
   "title": "Environment Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_environment_voltage{node=~\"$node\"}[$__interval])",
     "legendFormat": "{{node_long_name}} ({{node}})"
    }
   ]
  },
  {
   "title": "Environment Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_environment_current{node=~\"$node\"}[$__interval])",
     "legendFormat": "{{node_long_name}} ({{node}})"
    }
   ]
  }
 ]
}