{
 "title": "Meshtastic Telemetry (Nodes)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "source",
    "query": {
     "query": "meshtastic_node_info_last_heard"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Battery level",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meshtastic_telemetry_device_battery_level{source=\"$source\"}",
     "legendFormat": "{{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Battery level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_device_battery_level{source=\"$source\"}[$__interval])",
     "legendFormat": "Battery level {{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Device Voltage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meshtastic_telemetry_device_voltage{source=\"$source\"}",
     "legendFormat": "{{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_environment_temperature{source=\"$source\"}[$__interval])",
     "legendFormat": "Temperature {{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Barometric pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_environment_barometric_pressure{source=\"$source\"}[$__interval]) / 1.333",
     "legendFormat": "Barometric pressure {{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Environment Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_environment_voltage{source=\"$source\"}[$__interval])",
     "legendFormat": "Environment Voltage {{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Environment Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_environment_current{source=\"$source\"}[$__interval])",
     "legendFormat": "Environment Current {{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Channel util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_device_channel_utilization{source=\"$source\"}[$__interval])",
     "legendFormat": "Channel util {{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Air util tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_device_air_util_tx{source=\"$source\"}[$__interval])",
     "legendFormat": "Air util tx {{source_long_name}} ({{source}})"
    }
   ]
  }
 ]
}